"""Initial schema

Revision ID: 0cd7bbb8f4d5
Revises: 
Create Date: 2026-07-02 11:04:55.431135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd7bbb8f4d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('hr_contact_name', sa.String(), nullable=False),
    sa.Column('hr_contact_phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('active_backlogs', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('placed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('idx_students_branch_grad_year', ['branch', 'graduation_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)

    op.create_table('drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('package_lpa', sa.Float(), nullable=False),
    sa.Column('min_cgpa', sa.Float(), nullable=False),
    sa.Column('max_backlogs', sa.Integer(), nullable=False),
    sa.Column('eligible_branches', sa.JSON(), nullable=False),
    sa.Column('eligible_grad_years', sa.JSON(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.create_index('idx_drives_active_deadline', ['is_active', 'application_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_drives_id'), ['id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'drive_id', name='uq_student_drive_application')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('idx_applications_drive_id', ['drive_id'], unique=False)
        batch_op.create_index('idx_applications_student_id', ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_drive_id'), ['drive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_student_id'), ['student_id'], unique=False)

    op.create_table('interview_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_rounds_id'), ['id'], unique=False)

    op.create_table('interview_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_results_id'))

    op.drop_table('interview_results')
    with op.batch_alter_table('interview_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_rounds_id'))

    op.drop_table('interview_rounds')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_student_id'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_drive_id'))
        batch_op.drop_index('idx_applications_student_id')
        batch_op.drop_index('idx_applications_drive_id')

    op.drop_table('applications')
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drives_id'))
        batch_op.drop_index('idx_drives_active_deadline')

    op.drop_table('drives')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_id'))
        batch_op.drop_index('idx_students_branch_grad_year')

    op.drop_table('students')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
